### PR TITLE
Fix for chars > 126

### PR DESCRIPTION
**Pull request by vooor**
the way something like this :
var µlogged=µ('.jHeaderConnected');
won't minify to this :
varµlogged=µ('.jHeaderConnected');

it's probably a bug anyway a char will never be > 126 by itself

### CODE REVIEW

**Comment by twolfson** [comment]
Thanks for the fix, can you add tests for this as well?

**Comment by vooor** [comment]
I added tests for extended ascii but I'd like to add that, on my platform at least (node 4.2.1), if the newly added test validates (with the new patch), old tests "jquery" or "basic" are failing, with or without my patch.

**Comment by twolfson** [comment]
Cool, thanks =D

I will take a look at this by the end of the weekend

**Comment by twolfson** [comment]
Taking a look at this now. Side note, this repo is so old that I never set up Travis CI =o

**Comment by twolfson** [comment]
Alright, got `foundry` installed and Travis CI set up. After merging your PR, everything looks good to me.

This PR has been landed/released in `1.2.0`. Thanks for the patch!

**Comment by vooor** [comment]
thanks for the release, your lib may be old but it's still the fastest jsmin implementation for nodejs that I know and sometime it matter to be fast :)

**Pull request merged**
